services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  TRAW\Powermailautocomplete\:
    resource: '../Classes/*'

  TRAW\Powermailautocomplete\Domain\Model\Field:
    tags:
      - name: 'extender.extends'
        class: In2code\Powermail\Domain\Model\Field

  TRAW\Powermailautocomplete\Domain\Model\Form: 
    tags:
      - name: 'extender.extends'
        class: In2code\Powermail\Domain\Model\Form